networks:
    ntwk:
        driver: bridge

services:
    webapp:
        build:
            context: .
            dockerfile: docker/webapp/Dockerfile
        volumes:
            - ./application:/var/www/html
        depends_on:
            db:
                condition: service_healthy
            yarn:
                condition: service_started
        networks:
            - ntwk
        ports:
          - 8000:8000
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5

    yarn:
        build:
            context: .
            dockerfile: docker/yarn/Dockerfile
            args:
                HOST_UID: "${HOST_UID:-1000}"
                HOST_GID: "${HOST_GID:-1000}"
        volumes:
            - ./application:/app

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "umaSenhaSegura"
            MYSQL_USER: "mysql"
            MYSQL_DATABASE: "default"
            MYSQL_PASSWORD: "umaSenhaSegura"
        volumes:
            - ./local-data/db:/var/lib/mysql
        networks:
            - ntwk
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
            interval: 30s
            timeout: 10s
            retries: 5